services:
  cleaner:
    image: ghcr.io/tupinumboor/pipeline-cleaner
    container_name: pipeline-cleaner-local
    build: .
    restart: unless-stopped
    environment:
      DIR_MAX_AGE_DAYS: 2
    volumes:
      - ./workspace:/clean/1
